
package com.scoreport.service.idcheck;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ValidateAccountPortType", targetNamespace = "http://webservice.bqjr.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ValidateAccountPortType {


    /**
     * 
     * @param in2
     * @param in1
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.bqjr.com")
    @RequestWrapper(localName = "query", targetNamespace = "http://webservice.bqjr.com", className = "com.bqjr.webservice.Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://webservice.bqjr.com", className = "com.bqjr.webservice.QueryResponse")
    public String query(
        @WebParam(name = "in0", targetNamespace = "http://webservice.bqjr.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://webservice.bqjr.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://webservice.bqjr.com")
        String in2);

    /**
     * 
     * @param in2
     * @param in1
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.bqjr.com")
    @RequestWrapper(localName = "validate", targetNamespace = "http://webservice.bqjr.com", className = "com.bqjr.webservice.Validate")
    @ResponseWrapper(localName = "validateResponse", targetNamespace = "http://webservice.bqjr.com", className = "com.bqjr.webservice.ValidateResponse")
    public String validate(
        @WebParam(name = "in0", targetNamespace = "http://webservice.bqjr.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://webservice.bqjr.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://webservice.bqjr.com")
        String in2);

}
