
package com.scoreport.serviceclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IScoreTaskPortType", targetNamespace = "http://service.webservice.bqjr.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IScoreTaskPortType {


    /**
     * 
     * @param in2
     * @param in1
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.webservice.bqjr.com")
    @RequestWrapper(localName = "createTask", targetNamespace = "http://service.webservice.bqjr.com", className = "com.demo.client.CreateTask")
    @ResponseWrapper(localName = "createTaskResponse", targetNamespace = "http://service.webservice.bqjr.com", className = "com.demo.client.CreateTaskResponse")
    public String createTask(
        @WebParam(name = "in0", targetNamespace = "http://service.webservice.bqjr.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.webservice.bqjr.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.webservice.bqjr.com")
        String in2);

    /**
     * 
     * @param in2
     * @param in1
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.webservice.bqjr.com")
    @RequestWrapper(localName = "queryResult", targetNamespace = "http://service.webservice.bqjr.com", className = "com.demo.client.QueryResult")
    @ResponseWrapper(localName = "queryResultResponse", targetNamespace = "http://service.webservice.bqjr.com", className = "com.demo.client.QueryResultResponse")
    public String queryResult(
        @WebParam(name = "in0", targetNamespace = "http://service.webservice.bqjr.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.webservice.bqjr.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.webservice.bqjr.com")
        String in2);

}
