
package com.scoreport.serviceclient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import com.amarsoft.awe.Configure;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "IScoreTask", targetNamespace = "http://service.webservice.bqjr.com", wsdlLocation = "")
public class IScoreTask
    extends Service
{

    private final static URL ISCORETASK_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.scoreport.serviceclient.IScoreTask.class.getName());

    static {
        URL url = null;
        String scoretask_url = null;
        try {
            URL baseUrl;
            scoretask_url = Configure.getInstance().getConfigure("scoretask_url");
            baseUrl = com.scoreport.serviceclient.IScoreTask.class.getResource(".");
            url = new URL(baseUrl, scoretask_url);
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location:"+scoretask_url+", retrying as a local file");
            logger.warning(e.getMessage());
        } catch (Exception e) {
			e.printStackTrace();
		}
        ISCORETASK_WSDL_LOCATION = url;
    }

    public IScoreTask(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IScoreTask() {
        super(ISCORETASK_WSDL_LOCATION, new QName("http://service.webservice.bqjr.com", "IScoreTask"));
    }

    /**
     * 
     * @return
     *     returns IScoreTaskPortType
     */
    @WebEndpoint(name = "IScoreTaskHttpPort")
    public IScoreTaskPortType getIScoreTaskHttpPort() {
        return super.getPort(new QName("http://service.webservice.bqjr.com", "IScoreTaskHttpPort"), IScoreTaskPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IScoreTaskPortType
     */
    @WebEndpoint(name = "IScoreTaskHttpPort")
    public IScoreTaskPortType getIScoreTaskHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.webservice.bqjr.com", "IScoreTaskHttpPort"), IScoreTaskPortType.class, features);
    }

}
